#!/usr/bin/env python2.7
#
# hunktool
#
# the swiss-army knife for Amiga Hunk executable file format
#
# written by Christian Vogelgsang (chris@vogelgsang.org)

import os, sys
import argparse
import pprint

from amitools import Hunk
from amitools import ADFScanner

def show_hunks_brief(hunks):
  for hunk in hunks:
    print hunk['name']

def dump_hunks(hunks):
  pp = pprint.PrettyPrinter(indent=2)
  pp.pprint(hunks)

# ----- handle paths -----

def check_file(path, hunk_file, result):
  if result == Hunk.RESULT_OK:
    print path,"OK"
    if args.dump:
      dump_hunks(hunk_file.hunks)
  elif result == Hunk.RESULT_NO_HUNK_FILE:
    #print "No:",path,hunk_file.error_string
    pass
  elif result == Hunk.RESULT_INVALID_HUNK_FILE:
    print path,"Invalid:",hunk_file.error_string
    if args.dump:
      dump_hunks(hunk_file.hunks)
    sys.exit(1)
  elif result == Hunk.RESULT_UNSUPPORTED_HUNKS:
    print path,"Unsupported:",hunk_file.error_string
    if args.dump:
      dump_hunks(hunk_file.hunks)
    sys.exit(1)

def handle_adf_file(img_path,file_path,data):
  vpath = img_path + ":" + file_path
  hf = Hunk.HunkFile()
  result = hf.read_mem(vpath, data)
  check_file(vpath, hf, result)

def handle_adf(path):
  ADFScanner.scan_adf(path, handle_adf_file)

def handle_file(path):
  global args
  
  if path.endswith(".adf"):
    handle_adf(path)
    return
  
  hf = Hunk.HunkFile()
  result = hf.read_file(path)
  check_file(path, hf, result)

def handle_dir(path):
  for root, dirs, files in os.walk(path):
    for name in files:
      handle_file(os.path.join(root,name))
    for name in dirs:
      handle_dir(os.path.join(root,name))

def handle_path(path):
  if os.path.isdir(path):
    handle_dir(path)
  elif os.path.isfile(path):
    handle_file(path)
  
# ----- main -----
parser = argparse.ArgumentParser()
parser.add_argument('hunkfiles', nargs='+')
parser.add_argument('-d', '--dump', action='store_true', default=False, help="dump the hunk structure")
args = parser.parse_args()

for p in args.hunkfiles:
  handle_path(p)
print "done"
