#!/usr/bin/env python2.7
#
# vamospath [options] <path>
#
# a tool to convert between AmigaOS and native paths
#

import argparse
import os

from amitools.vamos.Log import *
from amitools.vamos.PathManager import PathManager

# --- preset args ---
vamos_prefix = os.path.join(os.environ['HOME'],".vamos")

# --- args ---
parser = argparse.ArgumentParser()
parser.add_argument('path', help="path to convert")
parser.add_argument('-v', '--verbose', action='store_true', default=False, help="be more verbos")
parser.add_argument('-l', '--logging', action='store', default=None, help="logging settings: <chan>:<level>,*:<level>,...")
parser.add_argument('-P', '--prefix', action='store', default=vamos_prefix, help="vamos directory prefix (%s)" % vamos_prefix)
parser.add_argument('-a', '--to-amiga', action='store_true', default=False, help="convert to amiga path")
parser.add_argument('-p', '--to-posix', action='store_true', default=False, help="convert to posix path")
args = parser.parse_args()
vamos_prefix = args.prefix

# --- setup logging ---
log_setup(args.logging)

# --- setup path manager ---
pm = PathManager(vamos_prefix)

if args.to_posix:
  print pm.ami_to_sys_path(args.path)
if args.to_amiga:
  print pm.sys_to_ami_path(args.path)