#!/usr/bin/env python2.7
#
# vamospath [options] <path>
#
# a tool to convert between AmigaOS and native paths
#

import argparse
import os

from amitools.vamos.Log import *
from amitools.vamos.PathManager import PathManager

# --- preset args ---
vamos_prefix = os.path.join(os.environ['HOME'],".vamos")

# --- args ---
parser = argparse.ArgumentParser()
parser.add_argument('op', help="path operation: a2s s2a abs parent current")
parser.add_argument('path', help="path to convert")
parser.add_argument('-v', '--verbose', action='store_true', default=False, help="be more verbos")
parser.add_argument('-l', '--logging', action='store', default=None, help="logging settings: <chan>:<level>,*:<level>,...")
parser.add_argument('-P', '--prefix', action='store', default=vamos_prefix, help="vamos directory prefix (%s)" % vamos_prefix)
args = parser.parse_args()
vamos_prefix = args.prefix

# --- setup logging ---
log_setup(args.logging)

# --- setup path manager ---
pm = PathManager(vamos_prefix)

op = args.op
if op == 'a2s':
  print pm.ami_to_sys_path(args.path)
elif op == 's2a':
  print pm.sys_to_ami_path(args.path)
elif op == 'abs':
  print pm.ami_abs_path(args.path)
elif op == 'parent':
  print pm.ami_abs_parent_path(args.path)
elif op == 'current':
  print pm.ami_abs_cur_path()
else:
  print "INVALID OPERATION:",op